### ISSUE TITLE
Query timeouts don't work in combination with gevent / set_wait_timeout

### ISSUE THREAD

**Issue by moagstar** [pymssql/pymssql#305]
You can reproduce this with the following code:

``` python
from gevent import monkey; monkey.patch_all()
from gevent import socket
import pymssql

if __name__ == '__main__':

    server = 'server_name_here'
    database = 'db_name_here'

    pymssql.set_wait_callback(lambda x: socket.wait_read(x))
    with pymssql.connect(server, '', '', database, timeout=10) as conn:
        with conn.cursor() as cursor:
            cursor.execute("WAITFOR DELAY '01:00'")
```

This blocks until the WAITFOR DELAY is complete.

I tried setting the timeout in the wait callback, this at least cancels the operation after the timeout period but the timeout exception is ignored:

``` python
from gevent import monkey; monkey.patch_all()
from gevent import socket
import pymssql

if __name__ == '__main__':

    server = 'server_name_here'
    database = 'db_name_here'

    pymssql.set_wait_callback(lambda x: socket.wait_read(x, timeout=10))
    with pymssql.connect(server, '', '', database) as conn:
        with conn.cursor() as cursor:
            cursor.execute("WAITFOR DELAY '01:00'")
```

Exception socket.timeout: timeout('timed out',) in '_mssql.db_sqlok' ignored

I also tried using a gevent timeout, but this exception is also ignored:

``` python
from gevent import monkey; monkey.patch_all()
from gevent.timeout import Timeout
from gevent import socket
import pymssql

if __name__ == '__main__':

    server = 'servername'
    database = 'catalog'

    pymssql.set_wait_callback(lambda x: socket.wait_read(x))
    with pymssql.connect(server, '', '', database) as conn:
        with conn.cursor() as cursor:
            with Timeout(10, Timeout):
                cursor.execute("WAITFOR DELAY '01:00'")
```

Exception gevent.timeout.Timeout: <Timeout at 0x2ade8a0 seconds=None> in '_mssql.db_sqlok' ignored

Is there some way I can determine that a timeout occured from the calling code?

I tested this using pymssql version 2.1.1

**Comment by fgarcialainez** [comment]
Hi,

I know this issue was posted more than 8 years ago, but please could you tell me if you found any workaround for this issue?

Thanks and Regards,

**Comment by termim** [comment]
I never used gevent myself, but I do not see any problem in the above examples. IMHO code behaves as it should.
Could you be more specific?

**Comment by fgarcialainez** [comment]
Hi @termim,

First of all, thanks for taking the time to answer my comment.

Basically the problem I am finding is that timeout param doesn't work properly in combination with gevent set_wait_callback tuning. 

As stated in the original comment, the execute call is blocked until the query finishes, so it seems that the timeout param is ignored. 

The only way I have achieved to "timeout" the query execution is to set a timeout in the socket.wait_read blocking call, but the problem here is that there is that there is a "socket.timeout" exception in the callback passed to set_wait_callback, not in the execute block. On this case, while it is true that the execute call returns, there is not any exception or error raised in that block (is this the intended behaviour?). The idea would be to catch this timeout exception and perform some kind of error handling like retry the operation, perform a rollback operation in the case of being in a transaction block, etc.

Thanks and Regards,

**Comment by termim** [comment]
Please try 2.2.8. It seems Cython 3.0 fixed exception propagation, it works for me locally now.

**Comment by fgarcialainez** [comment]
Hi @termim,

One more time, thanks for taking a look to this.

As far as I understand, the proposed approach to set query timeouts is to upgrade the library version to 2.2.8, and then set the timeout in the wait callback instead of using the timeout param available in the connection string / args. 

Taking a look to your last commits I understand that with this approach, the execute query función should raise if takes more time than the timeout set in the wait callback. 

Also I see that you have fixed the issue for Cython < 3.0.0, but the fix won’t be available until future releases of the library, etc. 

Is my understanding correct?

Thanks and Regards.

**Comment by termim** [comment]
It is up to you to select the best approach for you task. Just keep in mind that these timeouts are independent.
`timeout` in `connect` will set maximum time `FreeTDS` library waits for result, it is global for the entire connection.
`timeout` in the wait callback will set the maximum time `gevent` waits for the connection socket became readable, it is global while wait callback is not unset/changed. If you set both of them, then whichever is shorter will fire first. 

Yes, your understanding is correct AFAICS.

**Comment by fgarcialainez** [comment]
Ok so in theory both timeouts should work properly in version 2.2.8, right?

From your previous comment I understood that the fix was only in the set wait callback timeout exceptions propagation, not in the query timeout param.

Let me try the proposed version and will come back to you with my findings.

Thanks and Regards.

**Comment by fgarcialainez** [comment]
Hi @termim,

After downloading version 2.1.5 of the library, and apply your fix for Cython < 3.0.0 (thanks for this ;)) I can confirm my comments above.

As Python 3.5 is deprecated, I can understand that you don't consider releasing a potential 2.1.6 version including only this fix. On the other hand, I think that fixing the issue with the connection string / args timeout param should be in future releases.

Thanks and Regards,

**Comment by termim** [comment]
After carefully reviewing the code, I see that my previous explanation of the timeouts was incorrect.
The timeouts are **not** independent. Please see my revised comment above.
This is because `wait_read` is called first and is blocking. It either raises timeout exception or returns when result is available. Then `dbsqlok` is called and if result is available, then FreeTDS ignores timeout.
So, there is no issue here.

**Comment by fgarcialainez** [comment]
Hi @termim,

Well, I understand that you consider that there is not any issue here, but take into account that someone could think that connection string / args timeout will raise even in combination with wait_read timeout (may be it should be documented properly?).

For my use case, knowing that I should set the timeout in the wait_read, it is more than enough.

One more time, thanks for taking the time for handling this, really appreciate.

Regards,
