### ISSUE TITLE
header of setup.py has inconsistent copyright information (gpl v3) relative to pymssql project itself (lgpl v2.1)

### ISSUE THREAD

**Issue by tokenmathguy** [pymssql/pymssql#374]
To reduce confusion and likely increase adoption, the copyright used in the project should be made consistent.

**Comment by ramiro** [comment]
@damoxc, is the author of Cython-based pymssql v2 and who chose LGPL. He added the header to `setup.py` on 8e6ff1957b026108bb908db34fdc689c9d660540

Maybe he can shed some light on the situation?

**Comment by rsyring** [comment]
He also added the license file earlier that day with the LGPL license:

https://github.com/pymssql/pymssql/commit/44f731f73e76117b4c6f976db3c7566ffcb54921

and set the license to 'LGPL' in setup.py:

https://github.com/pymssql/pymssql/commit/e41bd26a94e462349526d4997fab9a303504325b

My guess is it's a typo.  But since the commit with the GPL came last in the sequence of events, we should try and get sign-off from him.

**Comment by damoxc** [comment]
I think the header of setup.py is what needs changing to be the LGPL header, my mistake at the beginning.

The original pymssql code from sourceforge was LGPL and the Cython code is all heavily based off of that, so you would need to get sign-off from the original authors.

**Comment by tokenmathguy** [comment]
damoxc@ Agreed. Updating the setup.py seems the more straightforward option and matches your intent. Since you're the author of setup.py, are you comfortable with changing it to be the LGPL header?

**Comment by damoxc** [comment]
Just submitted #375 which will resolve this. @rsyring fancy doing the honours?

**Comment by rsyring** [comment]
Merged #375, closing this issue.  Thanks @tokenmathguy for bringing this to our attention.
