### ISSUE TITLE
Release 2.1.2

### ISSUE THREAD

**Issue by msabramo** [pymssql/pymssql#381]
It looks like @ramiro has already gotten the ball rolling for a 2.1.2 release by committing the Changelog changes in https://github.com/pymssql/pymssql/pull/380. @ramiro of course has been doing excellent work for a long time now, as he has been the most active contributor by far I think. Thanks, @ramiro!

There are a few fixes that SurveyMonkey needs that are in git master and not yet in a release (with https://github.com/pymssql/pymssql/commit/6206686235ae711047e933e559adb2b3235d4c97 being the most critical one right now), so I would very much like to see a 2.1.2 release soon. I'm willing to help out with the release or if @ramiro has it under control and wants to do it by himself, that's fine with me too. Whatever works best for him.

I thought I'd just create a ticket to track it and put in a :+1: vote for doing the release. 

Cc: @sudarkoff, @bszonye, @pennyc

**Comment by ramiro** [comment]
Great idea @msabramo 

I think there are just few minor remaining tasks.

- [ ] Build and commit bundled x86 FreeTDS 0.95 static libs
- [ ] OS X wheels?
- [x] sdist tarball upload to PyPI release from Travis triggered by a tag
- [x] Windows wheels uploads to PyPI release from AppVeyor triggered by a tag
- [ ] Final changelog update
- [ ] Update changelog excerpt in projects's page at PyPI
- [ ] Update docs about item 1 above for Linux and what FreeTDS, openSSL DLLs are needed on Windows as well as the reationale to link them dynamically 

PS: I was planning to cut the release soon (.i.e. the next few days) but now there are some real life issues that might keep me form achieving this. If you hear no new from me on this fron please feel free to go ahead with the release.

**Comment by msabramo** [comment]
https://github.com/pymssql/pymssql/pull/382 ("Upload pypi releases from ci") -- nice!

**Comment by msabramo** [comment]
> Build and commit bundled x86 FreeTDS 0.95 static libs
@ramiro: It looks like you might've already done this with 6723f0c33db22c13a79b84e6c7e8b55a8c5b2e3a ?

**Comment by ramiro** [comment]
> @ramiro: It looks like you might've already done this with 6723f0c ?

Actually I only did the x86_64 part. Haven't got to learn how to + perform  the x85 (332 bits) part.

**Comment by msabramo** [comment]
Ah ok. Yeah I don't know off-hand either.

I wonder if we can get Travis to build them or something.

**Comment by ramiro** [comment]
I might have found how to build it, see #383. Will try to document this soon.

Re: Travis, it seems they don't have x86 build worker VMs: https://github.com/travis-ci/travis-ci/issues/986 and there is no a practical way (other than build things from source or install 3rd. party packages) to get e.g. a Python x86 instalaltion on the standard x86_64 ones 

So this would mean we can't use Travis to build x86 libs, but perhaps we can at least get the x86_64 ones by hacking the Travis integration you contributed to FreeTDS to deploy the artifacts somewhere in a way similar to whan't I'm doing for Windows using AppVeyor (https://github.com/ramiro/freetds/tree/freetds-0.95-for-pymssql). Something to play with for pymssql 2.2 :smiley: 

By the way, because of the same reason I actualy dont have a way to actually test a Linux x86 FreeTDS+Pythjon+pymssql stack as my workstation runs a x86_64 Ubuntu 14.04 system. So the binaries updated by #383 are untested.

**Comment by ramiro** [comment]
@msabramo @rsyring @damoxc It seems we are in good shape for the 2.1.2 release.

Can anyone of you take care of creating Mac OS X binaries so we can publish them as the offcial ones on PyPI? Or is this not so critical and we should try to get Homebrew to update their formula instead?

**Comment by damoxc** [comment]
@ramiro Not particularly elegant but wouldn't it be possible to use `debootstrap` to create a x86 chroot within the build environment, then use that to create x86 libraries?

Unfortunately I can't comment on the OS X aspect, I haven't ever owned OS X in my life.

**Comment by ramiro** [comment]
> @ramiro Not particularly elegant but wouldn't it be possible to use debootstrap to create a x86 chroot within the build environment, then use that to create x86 libraries?

Sound like a plan if one wants to generate these locally. Thanks for the advice.

**Comment by ramiro** [comment]
Fixed in 69850acb7bf52fe5d07a86d632e33fd889d54968
