### ISSUE TITLE
Begin Transaction, do stuff, Commit Transaction

### ISSUE THREAD

**Issue by rob-bb** [pymssql/pymssql#427]
Is it possible to do this in pymssql

	def start_transaction(self):
		self.logger.info(" Starting Transaction")
		self.cursor.execute("BEGIN TRANSACTION")

	def commit_transaction(self):
		self.logger.info(" Committing Transaction")
		self.cursor.execute("COMMIT TRANSACTION")

self.start_transaction()

self.cursor.execute("some sql here")
self.cursor.execute("more sql")
self.cursor.execute("and so on")

self.commit_transaction()

Because I cant seem to get it to work.  No errors, no data in the table after inserts.

**Comment by rsyring** [comment]
Please use the mailing list for this question, not issues.  You can find it
on Google groups.

Yes, it's possible.  Pymssql is always in a transaction.  Just run your sql
and then call commit on the connection.  I'm sure there are examples in the
docs or in the tests.

Randy Syring (sent from my mobile)
Chief Executive Developer
Direct: 502-276-0459
Office: 812-285-8766

Level 12 - Principled People | Software that Works

**Comment by rob-bb** [comment]
Ok, but this is an issue because it doesn't work.  using version 2.1.2 on python 3.5

I changed my commit_transaction() to be

	def commit_transaction(self):
		self.logger.info(" Committing Transaction")
		self.con.commit()

and still no data is entered into the table.  I need to turn autocommit on for it to enter data, but then it's entered for every sql statement I execute.  I can't run 100 insert statements and then send a commit statement.  So how would I then do a rollback if I need to?

**Comment by rsyring** [comment]
Please use the mailing list, check the docs, or look at the tests.

Randy Syring (sent from my mobile)
Chief Executive Developer
Direct: 502-276-0459
Office: 812-285-8766

Level 12 - Principled People | Software that Works
On May 7, 2016 12:34 AM, "rob-bb" <notifications@github.com> wrote:

Ok, but this is an issue because it doesn't work. using version 2.1.2 on
python 3.5

I changed my commit_transaction() to be

def commit_transaction(self):
    self.logger.info(" Committing Transaction")
    self.con.commit()

and still no data is entered into the table. I need to turn autocommit on
for it to enter data, but then it's entered for every sql statement I
execute. I can't run 100 insert statements and then send a commit
statement. So how would I then do a rollback if I need to?

—
You are receiving this because you modified the open/close state.

Reply to this email directly or view it on GitHub
<https://github.com/pymssql/pymssql/issues/427#issuecomment-217606247>
