### ISSUE TITLE
Pymssql (v2.1.2+) + Ubuntu 16.04 (freetds v0.95) Incompatible

### ISSUE THREAD

**Issue by drcrook1** [pymssql/pymssql#459]
Please see this stack overflow: 
Problem + Resolution is included.
http://stackoverflow.com/questions/39187089/tdsversion-keeps-defaulting-to-7-1-pymssql/39193758#39193758

**Comment by ramiro** [comment]
It's not clear what you are actually asking in that SO thread. Initially your problem seemed to be that you attempted to set TDS protocol 8.0 and you got 7.1 and thought that was a bug of some sort.

(I'm the one that answered there. Still can't post comments.)

You should have accepted the answer (or at least close the question) and post another one(s) for other issue(s) you are seeing. 

Now you seem to have mutated it to report that FreeTDS 0.95 is incompatible with Ubuntu 16.04 and that pymssql > 2.1.1 has some bug. I don't think that's correct.

Let me explain:

Unfortunately FreeTDS packages haven't been updated in Debian (and hence Ubuntu) for years and are stuck at 0.91. But these packages have at least one positive thing (and this is value provided by a Linux distribution): They are correctly dyamically linked against OpenSSL/GNUTLS so SSL support is there and it gets security updates every time OpenSSL gets a CVE.

Another aspect of your scenario intermixed in your question seems to be you want to connect to Azure (for which SSL support in FreeTDS is mandatory.)

Now, the staticalliy linked copy of FreeTDS 0.95 you get with our official 2.1.3 Wheel file has no SSL support because it would mean we need to also bundle OpenSSL or that our Wheel file wouldn't work in any Linux distribution as it gets tied to the OpenSSL version present on the releaser's system. Both options are undesirable.

This is an inherent and well known limitation (desgn compromise) of the Wheel Python packaging infrastructure: Users get a ready to use [pymssql] module by simply typing `pip install pymssql` without having to install FreeTDS, compile it and/or having to compile pymssql itself so it gets linked to FreTDS at build/install time.

But given the fact we can't get optional dependencies (e.g. SSL) we only cover the simplest scenario with these Wheel files: Unencrypted connections to a local (non-Azure) SQL Server DB. Any other more complex scenario need additional set up effort from the user.

You have solved your issue by downgrading pymssql to 2.1.1. This is because 2.1.3 is the first version for which we provide binary Wheels for Linux. When you install 2.1.1 the installation process links in your system-level FreeTDS 0.91 and everything works.

You could achieve something similar with pymssql 2.1.3 (or 2.1.2) by running something like (untested):
```
export PYMSSQL_DONT_BUILD_WITH_BUNDLED_FREETDS=1
pip install --no-binary pymsql pymssql==2.1.3
```

If you wished to use FreeTDS 0.95 you'd need to download, configure (making sure SSL feature is enabled), build and install it as per its documentation.

Then you'd be able to get pymssql to link against it by executing the same commands above.

**Comment by ramiro** [comment]
> If you wished to use FreeTDS 0.95 you'd need to download, configure (making sure SSL feature is enabled), build and install it as per its documentation.

Or for that matter, FreeTDS 1.0 or current FreeTDS development version.

**Comment by meet-bhagdev** [comment]
@ramiro what should an end user do to use SSL to enable Azure SQL DB connectivity with the latest version of pymssql?
