### ISSUE TITLE
Transactions behaviour

### ISSUE THREAD

**Issue by sunnyque** [pymssql/pymssql#460]
We debugged situation with transactions issues we faced and find out that pymssql opens transaction on connection start with "BEGIN TRAN" and after conn.commit() it commits already opened transaction and then open new one again.

It seems its a "feature" when autocommit settings is off. And this is VERY BAD practice to keep transaction open because of locks and concurrency between database connections. Of course your can write NOLOCK option for every SELECT in every program that uses this database but this is a bad practice too.

Its nice to see a way to start start transaction by programmers own choice ex. conn.begin() without any auto transaction features. This auto feature must be smart - it must detect a query that changes data and only then starts transaction just before executing query, there is already way in SQL Server to do that, it is called [IMPLICIT TRANSACTIONS](https://msdn.microsoft.com/library/ms187807.aspx) and you can use it - you only need to change query in commit to IF @@TRANCOUNT > 0 COMMIT TRAN and its gonna work really well

At least this moment must be shown in doc with **bold** because this cause a lot of problems

``` python
conn = pymssql.connect(server='server', user='sa', password='123456', database='tempdb')
cursor = conn.cursor()
cursor.execute("SELECT 'hello'")
conn.commit()
```

Profiler trace:

``` sql
use [tempdb]
go
BEGIN TRAN
go
SELECT 'hello'
go
COMMIT TRAN
go
BEGIN TRAN
go
```

I'm still kinda some shocked, please tell me 'm dreamin :)

**Comment by andreacassioli** [comment]
I think you are not dreaming

https://github.com/pymssql/pymssql/blob/master/src/pymssql.pyx#L284

**Comment by sunnyque** [comment]
Yes, We solved it by turning off "auto commit" feature, but at first it makes my eyes round. 

Also there is a hidden problem - this "auto commit" behavior will mess up every monitoring tool that evaluates transactions count per second because there is no real transactions but every connection is an transaction. this is really weird in terms of RDBMS

**Comment by andreacassioli** [comment]
I have the feeling that TRAN should just be removed, but I am not that confident making a PR for that. Any opinion from the maintainers??

**Comment by joshuahlang** [comment]
[ctds](https://pypi.python.org/pypi/ctds) uses IMPLICIT_TRANSACTIONS as you describe to implement a similar "auto commit" feature. It has mostly just been internally used and therefore doesn't have the coverage of running in other environments, but it may solve your transaction problem.

**Comment by rsyring** [comment]
I'm pretty sure this is the intended behavior by pymssql and any database driver that conforms to DB-API 2:

https://stackoverflow.com/questions/22019154/rationale-for-db-api-2-0-auto-commit-off-by-default
https://www.python.org/dev/peps/pep-0249/

**Comment by sunnyque** [comment]
yep, and someone else also mentioned 
> Auto commit is a bad thing and a pretty evil invention of ODBC

in my opinion it is better do not implement auto commit feature at all and force users to use their own transactions routine. 

anyway good to know this stuff to not run into again

**Comment by Chris2048** [comment]
@sunnyque 

> Yes, We solved it by turning off "auto commit" feature

Do you mean turning *on*? Seems the behavior described in the original post happened when it was off.

**Comment by sunnyque** [comment]
> @sunnyque
> 
> > Yes, We solved it by turning off "auto commit" feature
> 
> Do you mean turning _on_? Seems the behavior described in the original post happened when it was off.

yes, turning on. its a little mess with this feature. why auto commit must be turned on to stop using auto transactions

**Comment by Chris2048** [comment]
Hi all, just a note on this issue.

My own use-case was using pymssql with SQL-Alchemy, and [Flask-SQLAlchemy-Session](https://flask-sqlalchemy-session.readthedocs.io/en/v1.1/). Given my application only has one process per (uWSGI) worker, which would get its own Pool - there really doesn't need to be anymore than one connection per Pool, which got my wondering why there was even an open transaction.

After a bit of experimentation this is what I conclude - the first time the app instance connected, a connection was checked out from the Pool, a connection (and corresponding socket) made to the DB, and the process used this to make the queries to the DB for the lifetime of the request.

Once the request is done, per Flask-SQLAlchemy-Session, the session would be disposed of making it per-request.
the relevant line is:

    app.scoped_session.remove()

Then the connection would be checked back into the pool, *but the socket would remain open*.

You can see this on the MSSQL DB using 

```
SELECT sqltext.text AS query_text,
	sdec.local_net_address, sdec.local_tcp_port,
	sdec.client_net_address, sdec.client_tcp_port,
    sdes.[program_name], sdes.status, db_name(dbid) AS DatabaseName
FROM sys.dm_exec_sessions AS sdes
LEFT JOIN sys.dm_exec_connections AS sdec ON sdec.session_id = sdes.session_id
CROSS APPLY sys.dm_exec_sql_text(sdec.most_recent_sql_handle) AS sqltext
where sdes.session_id <> @@SPID
and program_name LIKE 'pymssql%'
and sqltext.text = 'BEGIN TRAN'
```

or on the server side using something like:

    lsof -i -P -n | grep <MSSQL server IP>:1433 | awk '{print $3,$1,$2,$9}'

so, basically, despite the session being dead, and the connection returned to the pool, the connection will still be connected to the DB. Note the SA option 'pool_recycle' doesn't help here, because although it might recycle the connection after a certain timeout, per [SA docs](https://docs.sqlalchemy.org/en/13/core/pooling.html):

    the invalidation only occurs during checkout

meaning while the worker is idle (or handles a request that doesn't hit the DB) it won't recycle the connection, which I expect is a limitation of SA not being able to actually execute code until is is called i.e. an idle worker with no requests to serve probably can't just stat itself up periodically to check its connections.

Anyway, the first fix I though of was using NullPool, which is a Pool type that doesn't persist connections. The problem is, I use temp tables, and this broke them. Turn out NullPool closes the connection per-query, which means using temp-tables across multiple queries in the same request doesn't work - plus I imagine the overhead of reconnecting might be add up for request that make multiple queries.

Ideally, I could make connection remain open (and reused) during a request, so I tried to make them per-request by modifying the above F-SA-Session code:

```
            engine = app.scoped_session().get_bind()
            app.scoped_session.remove()
            engine.dispose()
```

This worked! Now I can see the sockets close between requests.

Now, this should introduce a performance penalty, and I have yet to check if it is too severe.

If it is, I will have to figure out how to create some kind of socket timeout i.e. close sockets after a certain time of not being used, or after a certain amount of idle time. Or possibly to create a *true* inter-process connection Pool, which would mean connections may be used more efficiently, and DB access easier to limit.
