### ISSUE TITLE
Update documentation with hints for instillation under CYGWIN

### ISSUE THREAD

**Issue by RichardLangFromNZ** [pymssql/pymssql#463]
Tried to install pymssql into cygwin python install using pip.  There isn't currently any cygwin specific install instructions at http://pymssql.org but with a quick read it was obvious that pymssql has a dependency on FreeTDS that could be satisfied by installing FreeTDS package from the cygwin setup utility, however cygwin doesn't currently have any "freetds-dev" or "freetds-devel" package and it took quite a bit of head scratching to figure out the header files required by the pip build could be found in the the cygwin "libsybdb-devel" package

**Comment by KptainBiwouak** [comment]
I am facing still issues by trying to install  pymssql (2.1.3) from Cygwin (2.9.0 - x64 - Python 3.6.1) after having installed modules below:
 - freetds
 - libsybdb-devel
------------------------------------------------------------------------------------------------------------------
$ pip3 install pymssql
Collecting pymssql
  Using cached pymssql-2.1.3.tar.gz
Building wheels for collected packages: pymssql
  Running setup.py bdist_wheel for pymssql ... error
  Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/.gfmwk_tmp_061017075825_128/spectools/pip-build-x2sasj9g/pymssql/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /.gfmwk_tmp_061017075825_128/spectools/tmpynrr2cpnpip-wheel- --python-tag cp36:
  setup.py: platform.system() => 'CYGWIN_NT-10.0'
  setup.py: platform.architecture() => ('64bit', 'WindowsPE')
  setup.py: platform.libc_ver() => ('', '')
  setup.py: Not using bundled FreeTDS
  setup.py: include_dirs = []
  setup.py: library_dirs = ['/usr/local/lib']
  running bdist_wheel
  running build
  running build_ext
  building '_mssql' extension
  creating build
  creating build/temp.cygwin-2.9.0-x86_64-3.6
  gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -ggdb -O2 -pipe -Wimplicit-function-declaration -fdebug-prefix-map=/usr/src/ports/python3/python3-3.6.1-1.x86_64/build=/usr/src/debug/python3-3.6.1-1 -fdebug-prefix-map=/usr/src/ports/python3/python3-3.6.1-1.x86_64/src/Python-3.6.1=/usr/src/debug/python3-3.6.1-1 -ggdb -O2 -pipe -Wimplicit-function-declaration -fdebug-prefix-map=/usr/src/ports/python3/python3-3.6.1-1.x86_64/build=/usr/src/debug/python3-3.6.1-1 -fdebug-prefix-map=/usr/src/ports/python3/python3-3.6.1-1.x86_64/src/Python-3.6.1=/usr/src/debug/python3-3.6.1-1 -I/usr/include/python3.6m -c _mssql.c -o build/temp.cygwin-2.9.0-x86_64-3.6/_mssql.o -DMSDBLIB
  _mssql.c:266:22: fatal error: sqlfront.h: No such file or directory
   #include "sqlfront.h"
                        ^
  compilation terminated.
  error: command 'gcc' failed with exit status 1
-----------------------------------------------------------------------------------------------------------------

It seems sqlfront.h is missing.
Could you provide more guidelines in order to achieve successfully setup of this module?

**Comment by rsyring** [comment]
Supported platforms are Windows, Linux, and MacOS.  Cygwin is not officially supported, sorry.  Just not enough maintainer bandwidth.
