### ISSUE TITLE
Proposal to discontinue pymssql in favor of pyodbc

### ISSUE THREAD

**Issue by rsyring** [pymssql/pymssql#477]
From https://groups.google.com/forum/#!topic/pymssql/CLXHtLKBWig:

> Back when I started working with pymssql, pyodbc wasn't in very good shape.  However, Microsoft has just announced official support for pyodbc:
> 
> https://blogs.technet.microsoft.com/dataplatforminsider/2016/12/09/sql-server-python-whats-new/
> 
> * There are official pyodbc drivers from Microsoft for Linux: https://msdn.microsoft.com/en-us/library/hh568451(v=sql.110).aspx
> * FreeTDS also provides an ODBC driver.
> 
> With that announcement, it seems we might be fighting an up-hill battle to keep pymssql maintained.  Most users will gravitate towards pyodbc as the "official" solution for mssql.  We already struggle to attract enough developer talent to keep pymssql updated as recent issue requests for a new release show.

I only got once response on the ML and it agreed that pymssql should go.  

I want to start broadcasting this proposal to a larger audience, I'm thinking:

- Python Announce ML
- DB-Sig
- SQLAlchemy ML

------------

If anyone has solid technical reasons for why pymssql should be continued, please comment here.

**Comment by zzzeek** [comment]
I would need to crack open a large amount of old issues / failing tests / whatnot but pymssql in my experience works much better than pyodbc on a unix platform.    There were a lot of old issues w/ pyodbc that the maintainer was not able to address for me, these were probably on the old google code tracker and would need to be dug up again.   To my knowledge, SurveyMonkey is using pymssql still.   So unless I can get amazing support for pyodbc issues on unix (which I was not able to do before), I'd prefer pymssql keep up the good work.  Diversity only helps.

**Comment by agilevic** [comment]
At SlashDB we've had the best results with PyODBC, however not without pains. Various layers of the stack (FreeTDS, UnixODBC, PyODBC) had shown different problems at various times. Sometimes we had to compile some parts from sources and put them together to our liking, but as of last couple of years everything seems to be working fine from official packages. We have worked with MS SQL Server ODBC driver for Linux the least, however.

**Comment by damoxc** [comment]
@rsyring Discontinuing sounds like a rather drastic response... what benefit does discontinuing bring versus the current status quo?

**Comment by zzzeek** [comment]
@msabramo any comment on this?

**Comment by rsyring** [comment]
> Discontinuing sounds like a rather drastic response

Maybe it is and that is why I put the proposal out there, to get feedback.

> what benefit does discontinuing bring versus the current status quo?

If pyodbc is where Microsoft is directing people AND it matches or betters pyodbc features/performance/stability AND microsoft is going to be putting dev talent behind the Linux ODBC drivers and pyodbc AND pymssql has a hard time attracting enough dev talent to be maintained, then why not point people to a "better" option and focus efforts there?

That is, if we aren't adding value to the ecosystem, let's admit that.  **I'm not saying we aren't, I'm not convinced we aren't**, I just want to have a discussion about it.  :)

Also, if the proposal ends up being accepted, the repos and such wouldn't go away.  Someone else could always resurrect the project in the future if needed.  We would just admit it's not being developed anymore because pyodbc is the recommended backend for SQL Server in python.

> but pymssql in my experience works much better than pyodbc on a unix platform

That was my experience too, years ago.  I'm just wondering with Microsoft now putting out their own ODBC driver for Linux, their commitment to supporting MSSQL server on Linux, if pymssql is still the better option.

**Comment by zzzeek** [comment]
> If pyodbc is where Microsoft is directing people AND it matches or betters pyodbc features/performance/stability AND microsoft is going to be putting dev talent behind the Linux ODBC drivers and pyodbc AND pymssql has a hard time attracting enough dev talent to be maintained, then why not point people to a "better" option and focus efforts there?

Who's really pointing people anywhere?  The MySQL, Postgresql, and SQL Server databases have multiple DBAPI implementation available.  People pick the ones that work best.    And.... the end?       what is this discussion about ?   if MS wants to help build up CI servers and such that work on unix that run ODBC and SQLAlchemy test suites then great.    But right now this thread is basically about adding work for people like me.   Let's see every SQLAlchemy unit test running against ODBC with 100% success, remove all the "skips" for things that break, etc. on windows, unix, OSX.   Let's see that up on CI generously provided by microsoft.   Then this entire discussion has some meaning for me.  Otherwise I've no idea what we're doing.

**Comment by bkcsfi** [comment]
Does Microsoft prefer pyodbc only because it has the letters o, d, b and c in the name?

pyodbc on linux sounds like it adds at least 1, maybe 2 extra layers between a Python program and the database.  Despite the efforts of FreeTDS and UnixODBC to provide an 'odbc workalike' for Linux, it seems like an unnecessary layer of complexity to install and maintain.

The 'new MS' seems to like Linux as a workload via Azure and Docker on Windows Server. Perhaps they'd be willing to assist maintaining this project because it is certainly the more accepted and likely more 'performant' mysql database access method vs odbc on Linux.

**Comment by gordthompson** [comment]
@bkcsfi 

> Does Microsoft prefer pyodbc only because it has the letters o, d, b and c in the name?

Several years ago Microsoft started letting customers know that ODBC was being positioned to become the preferred method for non-Microsoft applications to interact with SQL Server. Prior to that, OLEDB was considered to be the "better" - but primarily Windows-centric - mechanism for SQL Server access, with ODBC support being maintained for "the other cases" (where OLEDB was not available). The new approach saw ODBC become the preferred mechanism, so it does makes sense that they would back an ODBC solution over a non-ODBC one.

> Perhaps they'd be willing to assist maintaining this project

I don't see why they would be interested if they already produce an ODBC driver for Linux and already have pyodbc as an officially supported way of using it from Python.

___

*p.s. re: "likely more 'performant'"* - Beware of heroic assumptions. I've only had the occasion to do one head-to-head comparison of pyodbc vs. pymssql and for that one test pyodbc turned out to be over 20 times faster. (Details in the Stack Overflow answer [here](http://stackoverflow.com/a/40156617/2144390).)

**Comment by jfabiani** [comment]
Dabo uses pymssql.  There is no support for pyodbc from the Dabo people.  And just for info I never did get pyodbc to work on a Mac.  So I do not want to drop pymssql.

**Comment by termim** [comment]
@gordthompson 
Your test was on Windows. What about Linux?

**Comment by termim** [comment]
@rsyring 
> If pyodbc is where Microsoft is directing people AND it matches or betters pyodbc 
> features/performance/stability AND microsoft is going to be putting dev talent behind the 
> Linux ODBC drivers and pyodbc AND pymssql has a hard time attracting enough dev talent 
> to be maintained, then why not point people to a "better" option and focus efforts there?

See how many ifs here, may be find out if they all true and only after that continue the discussion?

**Comment by rsyring** [comment]
> See how many ifs here, may be find out if they all true and only after that continue the discussion?

IMO, many of them are already answered.

* "If pyodbc is where Microsoft is directing people" already true.
* "microsoft is going to be putting dev talent behind the Linux ODBC drivers" already true
* "and pyodbc" not sure about this.
* "pymssql has a hard time attracting enough dev talent to be maintained" already true.

But the point of the proposal is to get other opinions and considerations regarding mssql's future.

**Comment by rsyring** [comment]
> And.... the end? what is this discussion about ? if MS wants to help build up CI servers and such that work on unix that run ODBC and SQLAlchemy test suites then great. But right now this thread is basically about adding work for people like me. Let's see every SQLAlchemy unit test running against ODBC with 100% success, remove all the "skips" for things that break, etc. on windows, unix, OSX. 

@zzzeek I believe your underlying question here is: does pyodbc have the same stability/reliability as pymssql across OS platforms.  The SA test suite is likely a good place to start when answering that question and before this proposal ends one way or the other, we should run those tests to see what the result is with a modern pyodbc and FreeTDS and Microsoft ODBC drivers.

**Comment by gordthompson** [comment]
@termim 

The purpose of that test was to verify that the SQL Server could re-use the execution plan for the queries sent by pyodbc+MS_ODBC but not for the queries sent by pymssql.

pymssql performs the parameter substitution before sending each query to the SQL Server ...

```sql
SELECT COUNT(*) AS n FROM table1 WHERE cola=0 AND colb=0 AND colc=0 AND cold=0
SELECT COUNT(*) AS n FROM table1 WHERE cola=0 AND colb=0 AND colc=0 AND cold=1
...
```

... and the command text is different each time so SQL Server cannot use the cached execution plan from the previous iteration.

On the other hand, pyodbc+MS_ODBC sends `exec sp_prepexec` statements with the same command text each time ...

```sql
SELECT COUNT(*) AS n FROM table1 WHERE cola=@P1 AND colb=@P2 AND colc=@P3 AND cold=@P4
```
... along with the parameter values for @P1 through @P4. Since the command text is the same, SQL Server can use the cached execution plan repeatedly.

I just verified that Microsoft's SQL Server ODBC Driver for Linux behaves the same way as its ODBC driver for Windows (as described for pyodbc+MS_ODBC, above). 

I also just verified that pyodbc+FreeTDS_ODBC performs the same "dynamic SQL" parameter substitution that pymssql does, so in that case it would not be able to take advantage of cached execution plans either. In fact, the SQL Profiler traces for pymssql and pyodbc+FreeTDS_ODBC are almost identical.

**Comment by damoxc** [comment]
> I also just verified that pyodbc+FreeTDS_ODBC performs the same "dynamic SQL" parameter substitution that pymssql does, so in that case it would not be able to take advantage of cached execution plans either. In fact, the SQL Profiler traces for pymssql and pyodbc+FreeTDS_ODBC are almost identical.

Nothing stopping us from implementing it though, actually seems like a relatively interesting mini-project

**Comment by gordthompson** [comment]
@damoxc 

> Nothing stopping us from implementing it though

Technically true, although the behaviour of FreeTDS_ODBC suggests that it might require a FreeTDS tweak instead of a pymssql tweak. However, given the change in Microsoft's support policy regarding SQL Server access from Python, the questions remain: 

1. Is it actually likely to happen?, and
2. Would it really be worth the effort?

... which is why Randy opened this issue in the first place.

**Comment by damoxc** [comment]
@gordthompson

1. Who knows if it will, but "shutting" the project down certainly won't help make it happen
2. Not really sure who gets to decide that other than the person willing to write it. If my time wasn't all tied up in my day job it is precisely the sort of thing that would interest me. Not for any particular reason other than the challenge of bringing the numbers closer together.

I think my feelings align quite closely with Andrzej, who sums it all up quite nicely in his post on the ML. 
https://groups.google.com/d/msg/pymssql/CLXHtLKBWig/ZvHUDECpBQAJ

**Comment by zzzeek** [comment]
Here is a [perfect example of why I have a very hard time with pyodbc](https://github.com/mkleehammer/pyodbc/issues/193).    Minor point update, 4.0.3->4.0.5.  cursor.execute() is *completely broken* for all u'' strings.    This is kind of the error I've had w/ pyodbc over and over for years - crashing on u'' strings.   It's like pyodbc is not tested at all before releasing.

**Comment by msabramo** [comment]
SurveyMonkey has been using pymssql for a long time with good results. A few folks looked at pyodbc and at Microsoft's driver and didn't h.ave luck. I think @sontek was probably the most recent to look at that and IIRC, he was running benchmarks and pyodbc (or maybe a Microsoft driver?) was core dumping under load.

That said, neither @sontek nor I work for SurveyMonkey anymore, so we can't speak for the current state of things there; only how things were at the time we were there

**Comment by sontek** [comment]
Yeah, I haven't tested pyodbc in over a year but the last time we evaluated pyodbc it had bugs, was slow, and just overall didn't work well.  I would suggest keeping `pymssql` around because it is truly the best driver out there based our our evaluation.  We tried pypyodbc, pyodbc, mxodbc, etc.

I did recently stumble upon a new one that people might want to try:

https://github.com/zillow/ctds

Obviously used at scale since it is Zillow and they actively maintain it.

**Comment by rsyring** [comment]
> https://github.com/zillow/ctds

Good find, I'll have to keep an eye on that project.  

IMO, the sentiment has trended away from deprecating pymssql in favor of pyodbc.  I don't believe any of the past maintainers were in favor.  @zzzeek also has strong feelings against it and given his extensive work with DBs b/c of SQLAlchemy, I have a hard time ignoring his recommendation.  The other opinions towards pyodbc were rarely positive with the exception being that it was possibly more performant.  

I'm withdrawing the proposal and will close the issue.  However, I do think pymssql is badly in need of a maintainer who can put regular time into the project.  I don't think it would need to be a lot, just regular.

**Comment by sakurai-youhei** [comment]
FYI: Please do not close pymssql (at least keep it as-is) for next years as I’ve already spent much time so far with it. ;) As for pyodbc, I can find only one advantage in it that is connection via named pipe; Others like SSL/NTLMv2 are manageable even with pymssql by tricking FreeTDS layer. Thanks.
