### ISSUE TITLE
Deprecation warning with 3.7

### ISSUE THREAD

**Issue by AlexHagerman** [pymssql/pymssql#576]
While working on the manylinux build I found this deprecation when importing pymssql in Python 3.7

```
__main__:1: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
```

Reproduce:

Python 3.7
pip install pymssql
```
python
import pymssql
```

**Comment by tonyravioli** [comment]
I'm seeing the same thing.

**Comment by tonyravioli** [comment]
Could it be that it's as simple as changing https://github.com/pymssql/pymssql/blob/891b20e29e4e247c17b202e8e34e5c739b6090ef/src/_mssql.pyx#L45 to
```
from collections.abc import Iterable
```
?

**Comment by AlexHagerman** [comment]
Hi @tonyravioli it's possible that's all we need to do. With 2.1.4 out and CI back up and running I'm taking a little bit of time away from dev with my newborn right now. Happy to review PRs though.

I think you're on the right track though based on: https://docs.python.org/3.7/whatsnew/3.7.html#id3

If you want to open up a PR for this with the change we can see how it looks in CI with build and test.

**Comment by montwell** [comment]
Still getting this warning in 2.1.4

**Comment by AlexHagerman** [comment]
The fix is in `master` and will be pushed out with `2.1.5` this was fixed after `2.1.4` release.

**Comment by turnovec** [comment]
Hi, when the version 2.1.5 could by available on PyPi?

**Comment by tonyravioli** [comment]
Is 2.1.5 going to be available in pip3?

**Comment by Bellaby** [comment]
I would love this fix to get rolled out. This would make things a lot easier compared to others I've seen but currently it doesn't work.

**Comment by UNIcodeX** [comment]
I, like seemingly many others, would like to know when a `pip install --upgrade pymssql` will result in the removal of this warning.

**Comment by n0mn0m** [comment]
I'm not actively working on the project, please see the [mailing list](https://groups.google.com/forum/#!topic/pymssql/6MZKgkKaYCE), and I'm not sure of the status for other past maintainers. 

I put out a call for help and documented what needs to happen for a [2.1.5 release](https://github.com/pymssql/pymssql/issues/632). Need to get CI caught up, update the docs for a release, and have somebody drive that forward. I closed the ticket after leaving it open for 4 months with no response. I have since moved on to other commitments and projects. I'm happy to chime in if somebody wants to pickup a shovel, otherwise the answer is that it will sit at `2.1.4`.
