### ISSUE TITLE
pymssql doesn't recognize and cleanup dead connections after failover with freetds 1.1

### ISSUE THREAD

**Issue by RetNick** [pymssql/pymssql#631]
Hello team. We're sailing into uncharted territory here at SurveyMonkey so some surprises are expected.

When SQL Server triggers a failover and our apps are running the following stack

>
SQLAlchemy: 1.1.9
pymssql: 2.1.4
TDS protocol: 7.4
FreeTDS: 1.1
OS: Ubuntu Bionic (18.04)

connections are not being recognized as dead and marked for cleanup as expected. This results in SQL Alchemy attempting to re-use the connections over and over, failing with errors at the freeTDS and pymssql boundary until the connections are eventually recycled when their TTL is reached. This happens for connections regardless of whether they are using availability group (i.e. multi-subnet) or non-availability group listeners.

After some digging, there seems to be a divide between the severity of the error being sent to pymssql's error handler from freeTDS, which relays message 20047 `DBPROCESS is dead or not enabled` as a severity level 1. Since the severity level is under the min_severity_level of 6, pymssql short-circuit returns an INT_CANCEL without checking if the connection is dead (https://github.com/pymssql/pymssql/blob/master/src/_mssql.pyx#L230), resulting in the aforementioned connection reuse behavior in SQL Alchemy.

I don't know enough about the severity levels and their intent to whether freetds should be specifying a higher severity level or in which library this issue should be fixed. However, we have been testing a pymssql build with the severity check moved down to after line 261 which seems to work, but I'm not sure of the implications of that besides what _seems_ to be a somewhat negligible amount of additional work due to the last msg var assignments and DBDEAD calls, the latter which seems to be only a few boolean checks on the underlying connection.

What are your thoughts? Does the fix belong in pymssql or freetds, and if the former, would something along the lines of the patch outlined above be acceptable? If so, I'll create a PR to get things started.

Thanks,
Jon

**Comment by AlexHagerman** [comment]
@JonSchuff thanks for the heads up. My understanding is that 1.1 released earlier this month (correct me if I'm wrong). While a PR to fix this in `pymssql` is probably needed I think we will also need to setup a matrix for testing TDS against 1.0 and 1.1 at the various protocol levels to be catching items like this. Can you create a test that verifies the updated behavior so that we can prevent regressions and test this against different versions/protocols? Since our CI is still on 1.0 with the protocol version set at 7.1 the test will only run against that, if you want to open an issue for updating the build to support FreeTDS 1.0 and 1.x as well as using the `auto` version or a matrix of versions for the protocol that would be appreciated.

https://github.com/FreeTDS/freetds/releases
http://www.freetds.org/userguide/choosingtdsprotocol.htm

**Comment by JonSchuff** [comment]
Np! Sure, I'll get acquainted with the existing test suite this afternoon if possible.

We're running with TDS v 7.4 btw- I'll add that to my original comment for specificity.

**Comment by AlexHagerman** [comment]
Sounds good. Right now `2.1.x` is using `appveyor` and `circleci`. Some work was done last year to move the Linux build to a docker container. There's more work that could be done around CI, but that's a separate ticket I could work on documenting since there are some other build items that should be addressed beyond the scope of this ticket.

**Comment by AlexHagerman** [comment]
@JonSchuff #632 may be of interest to you, and I would welcome feedback on gaps you see while testing your migration.

**Comment by JonSchuff** [comment]
@AlexHagerman finally found time to circle back to this- I'll post a PR with the aforementioned changes as well as create a separate issue for the additional CI testing variants.

**Comment by JonSchuff** [comment]
Side-note: looks like the `circleci` tests always run with the newest freeTDS release (freetds-patched.tar.gz) which is nice
