### ISSUE TITLE
Memory leak on RHEL (pymssql 2.2.1)

### ISSUE THREAD

**Issue by siloam** [pymssql/pymssql#713]
**Describe the bug**
Memory leak when working with db. Memory dump is performed.

**To Reproduce**
Try to connect and do queries and then you will see.

**Expected behavior**
Connection established. Pymssql 2.1.5 performs without such error.

**Current Behavior**
Memory dump. The driver is not working at all.

**Context (Environment)**
 - RHEL, Python 3.6

**Comment by termim** [comment]
Please provide more information:

- RHEL version
- how did you install it, if by pip then pip version
- when error happens - on connect, during querying etc.
- what exactly error do you see, "memory dump" is too vague.

**Comment by dblugeon** [comment]
Hello,
I don't know if it is a memory leaks, but i have this bug, too.

- RHEL 8.3
- python (rpm) 3.6.8
- installed by pip
- occured during the opening of the connection
- python interperter crashed with the message "Segmentation fault (core dumped)"

code to reproduce
`import pymssql; conn = pymssql.connect(user="user", password="password", host="localhost", database="master")`

For me, the last "good version" is also the 2.1.5. Versions 2.2.0, 2.2.1-dev0 and 2.2.1 are affected by the crash.

Thank you for your time.

**Comment by termim** [comment]
I do not have RHEL to test, so more information from your side is needed.
According to [distrowatch](https://distrowatch.com/table.php?distribution=redhat) RHEL-8.3 has Python 3.8.0.
You say you have 3.6.8. [distrowatch](https://distrowatch.com/table.php?distribution=redhat) says Python 3.6.8 is in RHEL-7.9.
That is confusing. Could you provide step by step instruction how did you install pymssql and where (Virtual environment or not).

Also could you try to run your script with the following environment and attach the log file here.
`export TDSDUMP=/tmp/freetds.log`

**Comment by dblugeon** [comment]
Hello,
I understand the confusion about python version on my vm and distrowatch. Rhel8 and centos8 are a concept of "module". Modules are a replacement for Red Hat Software Collections. And there are modules for python : 2.7, 3.6, 3.8. Informations about module are not on distrowatch. The website chooses to take the latest version available and not the default version (3.6)

It seems that the module 3.6 are enabled by default. We can have these two versions side by side. But python3 is a link to python3.6

My rhel environment is a vm under RedHat Virtualization.
my step to install pymsql are 

1. login as root on a vm with a running mssql instance
2. dnf -y install python3 python3-pip
2. pip3 install pymssql
3. python3 
4. import pymssql; conn = pymssql.connect(user="user", password="password", host="localhost", database="master")
5. crash dump

The crash can be reproduced on centos8, which can be more easy to test for you.
[freetds.log from centos8 python3.6](https://github.com/pymssql/pymssql/files/6492078/freetds.log)

my rediscover about modules are recent. So i test the case under python3.8 with following step

1. dnf module enable python38
2. dnf install -y python38
3. pip3.8 install pymssql
4. python3.8
5. import pymssql; conn = pymssql.connect(user="user", password="password", host="localhost", database="master")
6. no crash

So the problem seems occur under python 3.6 only.

**Comment by termim** [comment]
Could you try to do `pip -install -U pip` before installing pymssql for Python3.6?

**Comment by dblugeon** [comment]
Hello, 
I tried your suggestion and it works.  I don't have segfault anymore.
for information, centos and rhel 8 have pip in version 9 against 21.1.1 in the pypi project.

**Comment by termim** [comment]
That confirms that old pip does not pick correct wheel.
Put a note in the docs to update pip before installing from pypi.
Thanks for your testing!

**Comment by dblugeon** [comment]
Thank you for your time and your help.
